# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger:
  batch: 'true'
  branches:
    include:
      - '*'
resources:
  repositories:
    - repository: crux
      type: github
      name: ObjectivityLtd/crux
      ref: refs/tags/0.4.1
      #ref: refs/heads/feature/workbooks
      endpoint: crux

    - repository: tests
      type: github
      name: tfajks/jmeter_simple_test
      #ref: refs/tags/0.3.2
      #ref: refs/heads/feature/workbooks
      #ref: refs/tags/0.4.1
      endpoint: crux


parameters:
- name: debug
  type: boolean
  default: false

- name: mode
  default: jmeter_dynamic
  values:
    - tests
    - jmeter
    - jmeter_dynamic

- name: data_dir
  type: string
  default: path/to/jmeter/test_data

- name: jmeter_slaves
  default: 1
  type: number

- name: jmx
  default: path/to/jmeter/script/bing.jmx
  type: string

- name: jmeter_args
  default: "-Gthreads=1 -Gloops=1 -Gdata_dir=/shared"
  type: string

- name: kubernetes_service_connection
  default: k8
  type: string

- name: arm_service_connection
  default: mygroup
  type: string

variables:
  #test execution environment & config
  cluster_namespace: default
  kubernetesServiceConnection: ${{ parameters.kubernetes_service_connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  data_dir: $(repoName)/${{ parameters.data_dir }}
  data_dir_relative: ${{ parameters.data_dir }}
  crux_file: $(repoName)/path/to/jmeter/config/crux.properties
  thresholds_file: $(repoName)/path/to/jmeter/config/thresholds.properties
  workbooks_file: $(repoName)/path/to/jmeter/config/workbooks.properties
  jmeter_args: ${{ parameters.jmeter_args }}
  repoName: jmeter_simple_test
  cruxRepoName: crux
  scenario: $(repoName)/${{ parameters.jmx }}

  #parameters of cluster if to be created (jmeter_dynamic)
  armServiceConnection: ${{ parameters.arm_service_connection }}
  clusterNodeSize: Standard_D2_v2
  clusterNodeNumber: 2
  rgroup: jmeter-group
  namespace: default

jobs:
  - template: pipelines/azure/templates/run.mode.selector.yaml@crux
    parameters:
      mode: ${{ parameters.mode }}
      debug: ${{ parameters.debug }}
